package com.redhat.consulting_br.sampleproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Funcionario implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Funcionario() {
    }




}